name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: format particle_filter
      run: |
        cd particle_filter
        cargo fmt -- --check

    - name: build particle_filter
      run: |
        cd particle_filter
        cargo build --verbose

    - name: unit test particle_filter
      run: |
        cd particle_filter
        cargo test

    - name: format swarm_element
      run: |
        cd particle_filter/swarm_element
        cargo fmt -- --check

    - name: unit test swarm_element
      run: |
        cd particle_filter/swarm_element
        cargo test
