name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: format particle filter
      run: |
        cd particle_filter
        cargo fmt -- --check

    - name: build particle filter
      run: |
        cd particle_filter
        cargo build --verbose

    - name: unit test particle filter
      run: |
        cd particle_filter
        cargo test

    - name: format agents
      run: |
        cd particle_filter/agents
        cargo fmt -- --check

    - name: unit test agents
      run: |
        cd particle_filter/agents
        cargo test
